///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemoDesktop.DB_Management
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddDeleteRecording recording.
    /// </summary>
    [TestModule("409b3d44-595f-4108-9969-68c952110d34", ModuleType.Recording, 1)]
    public partial class AddDeleteRecording : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDemoDesktop.RxDemoDesktopRepository repository.
        /// </summary>
        public static global::RxDemoDesktop.RxDemoDesktopRepository repo = global::RxDemoDesktop.RxDemoDesktopRepository.Instance;

        static AddDeleteRecording instance = new AddDeleteRecording();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddDeleteRecording()
        {
            NOMBRE = "Karina";
            APELLIDO = "Masoko";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddDeleteRecording Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable NOMBRE.
        /// </summary>
        [TestVariable("16904046-0dd5-41ea-9ff7-7c6ab6005269")]
        public string NOMBRE
        {
            get { return repo.NOMBRE; }
            set { repo.NOMBRE = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable APELLIDO.
        /// </summary>
        [TestVariable("12f221f8-a850-491f-9424-17b9f778cd50")]
        public string APELLIDO
        {
            get { return repo.APELLIDO; }
            set { repo.APELLIDO = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.TestDatabase' at Center.", repo.RxMainFrame.TestDatabaseInfo, new RecordItemIndex(0));
            repo.RxMainFrame.TestDatabase.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.FirstName' at CenterLeft.", repo.RxMainFrame.RxTabStandard.FirstNameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard.FirstName.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NOMBRE'.", new RecordItemIndex(2));
            Keyboard.Press(NOMBRE, 10);
            Delay.Milliseconds(40);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.LastName' at CenterLeft.", repo.RxMainFrame.RxTabStandard.LastNameInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabStandard.LastName.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$APELLIDO'.", new RecordItemIndex(4));
            Keyboard.Press(APELLIDO, 10);
            Delay.Milliseconds(40);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.Abrir' at Center.", repo.RxMainFrame.RxTabStandard.AbrirInfo, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabStandard.Abrir.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Marketing' at Center.", repo.List1000.MarketingInfo, new RecordItemIndex(6));
            repo.List1000.Marketing.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.UpDownEdit' at CenterLeft.", repo.RxMainFrame.RxTabStandard.UpDownEditInfo, new RecordItemIndex(7));
            repo.RxMainFrame.RxTabStandard.UpDownEdit.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}28' with focus on 'RxMainFrame.RxTabStandard.UpDownEdit'.", repo.RxMainFrame.RxTabStandard.UpDownEditInfo, new RecordItemIndex(8));
            repo.RxMainFrame.RxTabStandard.UpDownEdit.PressKeys("{Back}28", 10);
            Delay.Milliseconds(70);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.RdbFemale' at Center.", repo.RxMainFrame.RxTabStandard.RdbFemaleInfo, new RecordItemIndex(9));
            repo.RxMainFrame.RxTabStandard.RdbFemale.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0') on item 'RxMainFrame.LblNumberOfPersonsNumber'.", repo.RxMainFrame.LblNumberOfPersonsNumberInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.RxMainFrame.LblNumberOfPersonsNumberInfo, "Text", "0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.BtnAddPerson' at Center.", repo.RxMainFrame.BtnAddPersonInfo, new RecordItemIndex(11));
            repo.RxMainFrame.BtnAddPerson.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1') on item 'RxMainFrame.LblNumberOfPersonsNumber'.", repo.RxMainFrame.LblNumberOfPersonsNumberInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.RxMainFrame.LblNumberOfPersonsNumberInfo, "Text", "1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.db_Person' at CenterLeft.", repo.RxMainFrame.RxTabStandard.db_PersonInfo, new RecordItemIndex(13));
            repo.RxMainFrame.RxTabStandard.db_Person.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.BtnDeletePerson' at Center.", repo.RxMainFrame.RxTabStandard.BtnDeletePersonInfo, new RecordItemIndex(14));
            repo.RxMainFrame.RxTabStandard.BtnDeletePerson.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0') on item 'RxMainFrame.LblNumberOfPersonsNumber'.", repo.RxMainFrame.LblNumberOfPersonsNumberInfo, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.RxMainFrame.LblNumberOfPersonsNumberInfo, "Text", "0");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
