///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemoDesktop.DB_Management
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddRecording recording.
    /// </summary>
    [TestModule("3f159fe7-6652-4641-bc45-1c8cdde084e1", ModuleType.Recording, 1)]
    public partial class AddRecording : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDemoDesktop.RxDemoDesktopRepository repository.
        /// </summary>
        public static global::RxDemoDesktop.RxDemoDesktopRepository repo = global::RxDemoDesktop.RxDemoDesktopRepository.Instance;

        static AddRecording instance = new AddRecording();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddRecording()
        {
            NOMBRE = "John";
            APELLIDO = "Walker";
            EDAD = "48";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddRecording Instance
        {
            get { return instance; }
        }

#region Variables

        string _EDAD;

        /// <summary>
        /// Gets or sets the value of variable EDAD.
        /// </summary>
        [TestVariable("c16cfc67-313b-468b-a7bf-f061afa987b2")]
        public string EDAD
        {
            get { return _EDAD; }
            set { _EDAD = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable AREA.
        /// </summary>
        [TestVariable("d9ab43d0-4bef-44fc-8d2b-0f497eb3f347")]
        public string AREA
        {
            get { return repo.AREA; }
            set { repo.AREA = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable GENERO.
        /// </summary>
        [TestVariable("bdd4ae4c-fcda-4412-9e97-e917b8ac23d6")]
        public string GENERO
        {
            get { return repo.GENERO; }
            set { repo.GENERO = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NOMBRE.
        /// </summary>
        [TestVariable("e091d946-b8ce-4260-b0a2-8868606240b9")]
        public string NOMBRE
        {
            get { return repo.NOMBRE; }
            set { repo.NOMBRE = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable APELLIDO.
        /// </summary>
        [TestVariable("3bc5e44b-2b86-4fd2-97cd-48b549c49264")]
        public string APELLIDO
        {
            get { return repo.APELLIDO; }
            set { repo.APELLIDO = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.TestDatabase' at 39;6.", repo.RxMainFrame.TestDatabaseInfo, new RecordItemIndex(0));
            repo.RxMainFrame.TestDatabase.Click("39;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.FirstName' at 64;7.", repo.RxMainFrame.RxTabStandard.FirstNameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard.FirstName.Click("64;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NOMBRE' with focus on 'RxMainFrame.RxTabStandard.FirstName'.", repo.RxMainFrame.RxTabStandard.FirstNameInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabStandard.FirstName.PressKeys(NOMBRE, 10);
            Delay.Milliseconds(60);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.LastName' at 32;6.", repo.RxMainFrame.RxTabStandard.LastNameInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabStandard.LastName.Click("32;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$APELLIDO' with focus on 'RxMainFrame.RxTabStandard.LastName'.", repo.RxMainFrame.RxTabStandard.LastNameInfo, new RecordItemIndex(4));
            repo.RxMainFrame.RxTabStandard.LastName.PressKeys(APELLIDO, 10);
            Delay.Milliseconds(40);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.Abrir' at 3;8.", repo.RxMainFrame.RxTabStandard.AbrirInfo, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabStandard.Abrir.Click("3;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Sales' at 155;4.", repo.List1000.SalesInfo, new RecordItemIndex(6));
            repo.List1000.Sales.Click("155;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.UpDownEdit' at 40;9.", repo.RxMainFrame.RxTabStandard.UpDownEditInfo, new RecordItemIndex(7));
            repo.RxMainFrame.RxTabStandard.UpDownEdit.Click("40;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '' on item 'RxMainFrame.RxTabStandard.UpDownEdit'.", repo.RxMainFrame.RxTabStandard.UpDownEditInfo, new RecordItemIndex(8));
            repo.RxMainFrame.RxTabStandard.UpDownEdit.Element.SetAttributeValue("Text", "");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$EDAD' with focus on 'RxMainFrame.RxTabStandard.UpDownEdit'.", repo.RxMainFrame.RxTabStandard.UpDownEditInfo, new RecordItemIndex(9));
            repo.RxMainFrame.RxTabStandard.UpDownEdit.PressKeys(EDAD, 10);
            Delay.Milliseconds(50);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.RdbGenero' at 8;7.", repo.RxMainFrame.RxTabStandard.RdbGeneroInfo, new RecordItemIndex(10));
            repo.RxMainFrame.RxTabStandard.RdbGenero.Click("8;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.BtnAddPerson' at 53;10.", repo.RxMainFrame.BtnAddPersonInfo, new RecordItemIndex(11));
            repo.RxMainFrame.BtnAddPerson.Click("53;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeRegex (Text~'[1-9]+') on item 'RxMainFrame.LblNumberOfPersonsNumber'.", repo.RxMainFrame.LblNumberOfPersonsNumberInfo, new RecordItemIndex(12));
            Validate.AttributeRegex(repo.RxMainFrame.LblNumberOfPersonsNumberInfo, "Text", new Regex("[1-9]+"));
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
